language: python
python:
- '3.8'
branches:
  only:
  - master
  - "/^v\\d\\.\\d\\.\\d/"
  - develop
  - pytest
  - pypi_package
install:
- python3 -m pip install --upgrade pip || python -m pip install --upgrade pip
- pip install pipenv
script:
- pipenv install --dev --skip-lock --system
- pipenv run pytest
- pipenv run all_black --check
jobs:
  include:
  - name: Python 3.8.0 on Xenial Linux
    python: 3.8
  - name: Python on macOS
    os: osx
    osx_image: xcode11.6
    language: shell
  - name: Python 3.8.5 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.8.5
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_deploy:
- pipenv install --system --skip-lock
- pipenv run python setup.py bdist_wheel
- pipenv --rm
- pipenv run pip install ./dist/*.whl
- mkdir output
- pipenv run python -m madplot graph
- ls -lsa ./output same_input_filename.png
deploy: 
  provider: pypi
  username: "__token__"
  password:
    secure: jCGnzvFh6BTPbma9pkJHQhUcCAQ/BimYAFKDXp1H3pgI/QCJOCH+mvlu4GsALpk+Neatb1ZWWIWHZxBpwiQhQgq/V3ZnnYbCD7bDvwU7nZnZhWdff6VhIprBMBoC3+94jxGuQ8+ThzqEXfbZsXl/MlHQ3qVUqZYje/n78Lr3359DzddTIhwX4SSMJ+SADyiD0LSB8eQeb+95oTraVEN5to5PTYGaIwegfg03l/2EpY3s+Psj1djf88a8p146TKbkEfmy2KouDOGDusCkC31KQMzQ7l7OAbuBnbjeEdCk84MOqCXVTjwWQu/UQG915JNXKaQEyU66/Fe8GDQShRrpODyYwBZEOqq8+UIqrLk5hmWGqEOIQqVCxzzk43FsD1v8Fg5dfSRJ/Yox+zbUvYufAtrq1THLUQq/+S64rq9YtwVlSyVEPGMldTjEPU/TqqM0otnd5wNP2NOx8Qa10xrcd8C6spWamL6GuGCh9Ebqv3sGhH8MKiTOTLzIWlGTB4bBbPqTpVTmkvdgDCKID9Ubwx15aXsR9hFglKifuS8Qgy/38KZ/LYdt4ctpj7/HzUP3ly5MhkL0lahl/f5mFVRc4Kn4DekscmPWHbF3HVUp1PtGwIXaAqU5izh2VwQpQ0N+cJcg31XTmU3uVM4bcmNWJv+9l9BUybYQa6xrMvsK2Xw=
  on:
    repo: "${TRAVIS_REPO_SLUG}"
    tags: true
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
